### ISSUE TITLE
Tracking Issue for UI Nitpicks 

### ISSUE THREAD

**Issue by mobile-bungalow** [kalix-systems/herald#71]
This issue should be used to document and eliminate small UI issues that do not constitute bugs but still break UX. Please comment new issues instead of editing this comment.

**Usability**
- [x] Most/all of the buttons should show informative tooltips on hover (on mobile this should probably happen on long press)

**Mobile**
- [ ] margins should match the designs, this may mean trying some new values until they work (colleen will deal with this)

**Group creation**
- [x] after a group is created, it should be loaded as the current chat view with the message compose field focused (can be handled as a signal from libherald when some stuff is settled on the backend)

**Settings**
- [x] Grid layout for settings should align all interactive elements in one column (may need to refactor how settings is set up for this)
- [x] The buttons in the settings menu are unstyled , use some kind of material design
- [x] Language settings and preferred disappearing time settings should match appearance-wise

**TextAreas**
- [ ] Use system palette for highlight color and highlighted text color (can't be done until we think about integrating with the system palette better in dark mode)
- [x] All text input fields should be the full width of any underline they have (so that clicking above the underline focuses the input even if there isn't placeholder text there)
- [x] Default TextArea behavior should include, moving focus to parent on ESC, ctrl+A support, ctrl+E support

**Gallery Viewer**
- [x] Zooming in and out does not consistently centre the image - it jumps to the side

**Emoji Picker**
- [x] The borders of the lowest divider on the emoji picker spill over the sides
- [x] Larger hover background for emojis
- [x] Currently mousing over the emojis causes the highlight for chat bubbles behind the picker to flicker, this is probably caused by the emojis intermittently capturing hover events for the chat bubbles
- [x] Scroll Velocity on the emoji picker on linux is too fast.

**Login Flow**
- [x] Error messages should be represented in the UI, not in a native dialog

**Chat bubbles**
- [x] The list of file attachments should be an expand/collapse view, not a scrollview
- [x] Clicking the reply button should move focus to the message compose field so the user can start typing immediately

**Chat view**
- [x] Both deleting a message and clearing the message history should bring up a popup confirming the action before executing it.

**Comment by mobile-bungalow** [comment]
**Image Viewer**
- [ ] Use the provided SVG icons with the tool buttons
- [ ] Fill in stub for reset, which should reset the size of the window to undefined, so that the next selected image can redefine it.
- [ ] Pinch & Scroll support on linux, as well as sane flick velocities

**Comment by BaeoMaltinsky** [comment]
> Error messages should be represented in the UI, not in a native dialog

This is somewhat done now, but I'm still showing the pop-ups for connection/serialization based errors by default because they're more informative for debugging.

**Comment by BaeoMaltinsky** [comment]
> Default TextArea behavior should include, moving focus to parent on ESC, ctrl+A support, ctrl+E support, Use system palette for highlight color and highlighted text color

^A and ^E seem to be supported by default on Linux on every text input I've tried them on. Is this not the case on macOS?

**Comment by kaavyajayram** [comment]
ctrl A is supported on macOS too by default, not sure about ctrl E

**Comment by BaeoMaltinsky** [comment]
It seems that it is, marking that as done.

**Comment by mobile-bungalow** [comment]
Closing this issue as the remaining two tasks won't be filled / are ongoing tasks.
